### ISSUE TITLE
engine.io-client-java 0.6.1 -> 'websocket error' -- SocketTimeoutException

### ISSUE THREAD

**Issue by danpe** [socketio/engine.io-client-java#32]
Hey,

Since I updated to `socket.io-client-java 0.6.1` which uses `engine.io-client-java 0.6.1` I keep getting
 `'websocket error' -- SocketTimeoutException` 
every few (10-15) seconds after a successful connection.

```
W/System.err﹕ java.net.SocketTimeoutException
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.Okio$2.read(Okio.java:139)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.request(RealBufferedSource.java:71)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.require(RealBufferedSource.java:64)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:95)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:171)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
```

Than reconnecting also successful but after few seconds error again.
I'm in a loop of connections and disonnections..

Here is my server settings:
```javascript
// Start the server
var app     = express();
var server = app.listen(port);

var io = require('socket.io')(server, {
  'log level': 2,
  'polling duration': 10,
  'close timeout': 12,
  'heartbeat timeout': 30,
  'heartbeat interval': 5,
  'cookie': false
});
```

I'm having like a singelton socket in my Android App, here is function that creates it:
```Java
private Socket createSocket() {
        IO.Options opts = new IO.Options();
        opts.timeout = 10000;
        opts.forceNew = true;
        opts.reconnection = true;
        opts.multiplex = true;
        opts.reconnectionAttempts = Integer.MAX_VALUE;

        try {
            mSocket = IO.socket(mServerUrl, opts);
            registerEvents();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

        isConnected = false;

        return mSocket;
}
```
Any ideas?

**Comment by b95505017** [comment]
https://github.com/square/okhttp/commit/0de14e992c228fd9de9fe78417788131bee00902
OkHttp 2.5.0 now add default timeout 10s, maybe try to enlarge the timeout threshold or just turn it off.

**Comment by nkzawa** [comment]
Umm, maybe we should turn it off. Thanks for your report.

**Comment by nkzawa** [comment]
0.6.2 is out.

**Comment by b95505017** [comment]
I'm still curious why add the default timeout will cause this issue. :(
