### ISSUE TITLE
IndexOutOfBoundsException on decoding payload

### ISSUE THREAD

**Issue by KrawczykPawel** [socketio/engine.io-client-java#70]
on version 0.8.1

`Fatal Exception: java.lang.IndexOutOfBoundsException: index=5, limit=5
       at java.nio.Buffer.checkIndex(Buffer.java:156)
       at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:115)
       at io.socket.engineio.parser.Parser.decodePayload(Parser.java:211)
       at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
       at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
       at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
