### ISSUE TITLE
IllegalStateException "closed" on sending Message

### ISSUE THREAD

**Issue by KrawczykPawel** [socketio/engine.io-client-java#71]
on version 0.8.1

Fatal Exception: java.lang.IllegalStateException: closed
       at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:107)
       at io.socket.engineio.client.transports.WebSocket$4.call(WebSocket.java:189)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
       at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:184)
       at io.socket.engineio.client.Transport$3.run(Transport.java:108)
       at io.socket.thread.EventThread.exec(EventThread.java:55)
       at io.socket.engineio.client.Transport.send(Transport.java:103)
       at io.socket.engineio.client.Socket.flush(Socket.java:615)
       at io.socket.engineio.client.Socket.onDrain(Socket.java:606)
       at io.socket.engineio.client.Socket.access$1100(Socket.java:31)
       at io.socket.engineio.client.Socket$6.call(Socket.java:308)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)

**Comment by nkzawa** [comment]
Should be fixed on 0.8.2
